services:
  minecraft-server:
    image: itzg/minecraft-server
    stdin_open: true
    tty: true
    volumes:
      - ./data:/data
    ports:
      - 25565:25565
    environment:
      EULA: true
      TYPE: PAPER
      USE_AIKAR_FLAGS: true
      VERSION: 1.8.8