services:
  minecraft-server:
    platform: linux/x86_64
    build:
      dockerfile: Dockerfile
      context: .
    stdin_open: true
    volumes:
      - ./data:/data
      - ./data/RewiBW/:/server/plugins/RewiBW/
    ports:
      - 25565:25565
    environment:
      EULA: true
      AIKAR_FLAGS: true
      ANTI_REDUCE: true