services:
  minecraft-server:
    build:
      dockerfile: Dockerfile
      context: .
    stdin_open: true
    tty: true
    volumes:
      - ./data/maps:/data/maps
      - ./data/lobby:/rewibw/lobby
    ports:
      - 25565:25565
    environment:
      EULA: true
      AIKAR_FLAGS: true