[libraries]
spigot = { group = "org.spigotmc", name = "spigot", version = "1.8.8-R0.1-SNAPSHOT" }
effectlib = { group = "com.github.Slikey", name = "EffectLib", version = "5.10-SNAPSHOT" }
javassist = { group = "org.javassist", name = "javassist", version = "3.27.0-GA" }
# Cannot be used in subproject scope
lombok = { group = "org.projectlombok", name = "lombok", version = "1.18.30" }
