api-version: 1.8.8
author: Marfien
name: RewiBW-SetupTool
version: 1.0.0
main: dev.marfien.rewibw.setuptool.SetupToolPlugin

commands:
  setup:
    description: Setup a new map
    usage: /setup <mapName>
    permission: rewibw.setup
  save:
    description: Save the current map
    usage: /save [path]
    permission: rewibw.save