api-version: 1.8.8
author: Marfien
name: rewi-bw-setup
version: @version@
main: dev.marfien.rewibw.setuptool.SetupToolPlugin

commands:
  setup:
    description: Setup a new map
    usage: /setup <mapName>
    permission: rewibw.setup
  save:
    description: Save the current map
    usage: /save [path]
    permission: rewibw.save
  exit:
    description: Exit the setup
    usage: /exit
    permission: rewibw.exit
  to-world:
    description: Teleport to the world
    usage: /to-world
    permission: rewibw.toworld
  get-items:
    description: Get the items
    usage: /get-items
    permission: rewibw.getitems
  set-border:
    description: Set the border
    usage: /set-border <x1> <x2> <z1> <z2>
    permission: rewibw.setborder