FROM anti-reduce-server

RUN mkdir plugins && wget -O plugins/NoteBlockAPI.jar https://jitpack.io/com/github/koca2000/NoteBlockAPI/1.6.2/NoteBlockAPI-1.6.2.jar

COPY build/libs/*-all.jar plugins/rewibw.jar