on:
  workflow_call:
    inputs:
      task:
        type: string
        required: true
        description: 'The task to run'
      extra_flags:
        type: string
        required: false
        default: ''
        description: 'Extra flags to pass to the task'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          cache: 'gradle'
          java-version: '8'
      - name: Get Maven cache
        uses: actions/cache@v4
        id: cache-maven
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven
      - name: Install Spigot in local maven repo
        if: steps.cache-maven.outputs.cache-hit != 'true'
        run: |
          wget -O BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
          java -jar BuildTools.jar --rev 1.8.8
      - name: Gradle ${{ inputs.task }}
        run: ./gradlew ${{ inputs.extra_flags }} clean ${{ inputs.task }} --no-daemon --parallel
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: '**/build/**/*'