name: Build
run-name: Build '${{ github.ref_name }}' for Commit ${{ github.event.head_commit.message }}

on:
  push:
    branches-ignore:
      - main
      - develop

env:
  TAG: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          cache: 'gradle'
          java-version: '8'
      - name: Get Maven cache
        uses: actions/cache@v4
        id: cache-maven
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven
      - name: Install Spigot in local maven repo
        if: steps.cache-maven.outputs.cache-hit != 'true'
        run: |
          wget -O BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
          java -jar BuildTools.jar --rev 1.8.8
      - name: Test with Gradle
        run: ./gradlew clean check --no-daemon --parallel
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: '**/build/libs/*.jar'