name: Build
run-name: Build '${{ github.ref_name }}' for Commit ${{ github.event.head_commit.message }}

on:
  push:
    branches-ignore:
      - main
      - develop

env:
  TAG: ${{ github.ref_name }}

jobs:
  build:
    uses: ./.github/workflows/util/build-with-gradle.yml
    with:
      task: 'check'