name: Publish on Docker Hub
run-name: Publish version ${{ github.ref_name }}

on:
  push:
    branches:
      - main
      - develop
    tags:
      - *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set TAG variable
        run: echo ::set-env name=TAG::$(echo $GITHUB_REF | cut -d '/' -f 3)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64
      - name: Build and push
        uses: docker/bake-action@v4
        with:
          push: true