name: Publish on DockerHub
run-name: Publish '${{ github.ref_name }}' for Commit '${{ github.event.head_commit.message }}'

on:
  push:
    tags:
      - '*'
    branches:
      - main
      - develop

env:
  TAG: ${{ github.ref_name }}

jobs:
  build:
    uses: ./.github/workflows/build-with-gradle.yml
    with:
      task: 'shadowJar'
      extra_flags: -PprojectVersion='${{ github.ref_type == 'branch' && '{version}-' }}${{ github.ref_name }}'

  publish:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base-image:
          - eclipse-temurin:8-jre
          - eclipse-temurin:8-jre-alpine
          - eclipse-temurin:8-jdk
          - eclipse-temurin:8-jdk-alpine
        include:
          - base-image: eclipse-temurin:8-jre
            tag-suffix: ''
            set: |
              *.platform=linux/amd64
              *.platform=linux/arm64
          - base-image: eclipse-temurin:8-jre-alpine
            tag-suffix: '-alpine'
            set: |
              *.platform=linux/amd64
          - base-image: eclipse-temurin:8-jdk
            tag-suffix: '-jdk'
            set: |
              *.platform=linux/amd64
              *.platform=linux/arm64
          - base-image: eclipse-temurin:8-jdk-alpine
            tag-suffix: '-jdk-alpine'
            set: |
              *.platform=linux/amd64
    env:
      TAGS: |
        type=ref,event=branch
        type=ref,event=tag
        type=sha
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=semver,pattern={{major}}
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64
      - name: Docker metadata server
        uses: docker/metadata-action@v5
        id: meta-server
        with:
          images: marfiens/rewibw-server
          tags: ${{ env.TAGS }}
          flavor: |
            suffix=${{ matrix.tag-suffix }}
          bake-target: docker-metadata-action-server
      - name: Docker metadata setup-tool
        uses: docker/metadata-action@v5
        id: meta-setup-tool
        with:
          images: marfiens/rewibw-setup-tool
          tags: ${{ env.TAGS }}
          flavor: |
            suffix=${{ matrix.tag-suffix }}
          bake-target: docker-metadata-action-setup-tool
      - name: Build and push
        uses: docker/bake-action@v4
        env:
          BASE_IMAGE: ${{ matrix.base-image }}
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.meta-server.outputs.bake-file }}
            ${{ steps.meta-setup-tool.outputs.bake-file }}
          push: true
          pull: true
          set: |
            ${{ matrix.set }}
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
