name: Create GitHub Release
run-name: Create GitHub Release '${{ github.ref_name }}' for Commit '${{ github.event.head_commit.message }}'

on:
  push:
    tags:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/build-with-gradle.yml
    with:
      task: 'shadowJar'
      extra_flags: -PprojectVersion='${{ github.ref_type == 'branch' && '{version}-' }}${{ github.ref_name }}'

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            README.md
            anti-reduce-agent/build/libs/*.jar
            bedwars/build/libs/*.jar
            map-setup-tool/build/libs/*.jar